apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: some-nginx
    component: web
spec:
  containers:
  - name: some-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
